Issue 41 - main.defaultGpkg() test coverage - take 2!
go-spatial/go-wfs pull request #67
Opened 2018-04-11 12:04 UTC by jlucktay

From #41 and based on a non-malfunctioning branch this time. 👍

2018-04-11 22:04 UTC, JivanAmara requested changes
Looks good.  A few minor changes.  Don't forget to add your name to the copyright section of files you modify & remove other devs names from files that they didn't contribute to ( yet ;-) ).

2018-04-11 22:04 UTC, JivanAmara commented on util.go
> +//
Add your John Hancock here.

2018-04-11 22:04 UTC, JivanAmara commented on util_test.go
> +	for _, c := range cases {
Collect the index here...

2018-04-11 22:04 UTC, JivanAmara commented on util_test.go
> +			t.Errorf("Could not change working directory to '%s'.", casePath)
...and prefix error messages w/ [<case index>]

2018-04-11 22:04 UTC, JivanAmara commented on util_test.go
> +			t.Errorf("Under '%s', defaultGpkg() == '%s', wanted '%s'.", casePath, got, c.dummyFileName)
...and prefix error messages w/ [<case index>]

2018-04-12 10:01 UTC, jlucktay commented
OK, all done @JivanAmara 👍

2018-04-12 19:52 UTC, JivanAmara commented
@jlucktay All tests passing?

2018-04-13 23:40 UTC, JivanAmara commented
@jlucktay ping, tests passing?

2018-04-14 07:54 UTC, jlucktay commented
They were passing when I last committed, but now there is a problem in the `data_provider` package with `geom.Extent`.

2018-04-14 08:46 UTC, jlucktay commented
All sorted. Passing on MacOS and Windows both!

2018-04-16 18:40 UTC, JivanAmara commented
Great, will merge.  Appreciate your help, if you've got more time & interest I'd love to have you take on another piece :-)

2018-04-16 18:40 UTC, merged